// generated by deep-copy -pointer-receiver -o types_deepcopy.go --type SampleLarge --type SampleSmall .; DO NOT EDIT.

package serialize

// DeepCopy generates a deep copy of *SampleLarge
func (o *SampleLarge) DeepCopy() *SampleLarge {
	var cp SampleLarge = *o
	if o.Glossary.GlossDiv.GlossList.GlossEntry.GlossDef.GlossSeeAlso != nil {
		cp.Glossary.GlossDiv.GlossList.GlossEntry.GlossDef.GlossSeeAlso = make([]string, len(o.Glossary.GlossDiv.GlossList.GlossEntry.GlossDef.GlossSeeAlso))
		copy(cp.Glossary.GlossDiv.GlossList.GlossEntry.GlossDef.GlossSeeAlso, o.Glossary.GlossDiv.GlossList.GlossEntry.GlossDef.GlossSeeAlso)
	}
	return &cp
}

// DeepCopy generates a deep copy of *SampleSmall
func (o *SampleSmall) DeepCopy() *SampleSmall {
	var cp SampleSmall = *o
	if o.Values != nil {
		cp.Values = make([]*string, len(o.Values))
		for i := range o.Values {
			if o.Values[i] != nil {
				cp.Values[i] = new(string)
				*cp.Values[i] = *o.Values[i]
			}
		}
	}
	return &cp
}
